PS_CLEAN_MODE_RUNNING = 'CleanMdRunning'
PS_COLD_KEEP_MD_RUNNING = 'ColdKeepMdRunning'
PS_COLD_STOR_MD_RUNNING = 'ColdStorMdRunning'
PS_PROD_MD_RUNNING = 'ProdMdRunning'
PS_MODE_STATUS_IND = 'ModeStatusInd'
PS_JBT_MODE_HETA_RUN = 'HeatModeRunning'    #GCO
PS_JBT_MODE_STEAM_RUN = 'SteamModeRunning'  #GCO
PS_JBT_MODE_RUNNING = 'OvenRunning'         #GCO
PS_JBT_HEAT_RUN= 'JBT_MODE_HEAT_RUN'        #TDO
PS_JBT_STEAM_RUN='JBT_MODE_STEAM_RUN'       #TDO
PS_JBT_RUNNING='JBT_MODE_RUNNING'           #TDO


production_state_tags = [
    PS_CLEAN_MODE_RUNNING,
    PS_COLD_KEEP_MD_RUNNING,
    PS_COLD_STOR_MD_RUNNING,
    PS_PROD_MD_RUNNING,
    PS_MODE_STATUS_IND,
    PS_JBT_MODE_HETA_RUN,
    PS_JBT_MODE_STEAM_RUN,
    PS_JBT_MODE_RUNNING,
    PS_JBT_HEAT_RUN,
    PS_JBT_STEAM_RUN,
    PS_JBT_RUNNING,
]
