CS_CLEAN_MODE_RUNNING = 'CleanMdRunning'
CS_CLEAN_MODE_SELECTED = 'CleanMdSeld'
CS_SYSTEM_MASTER_STOP = 'SysMstrStop'
CS_SYSTEM_MASTER_STOP_PB = 'SysMstrStopPB'
CS_SYSTEM_MASTER_STOP_SW = 'SysMstrStopSw'
CS_CIP_INSPECTION_PAUSE = 'CIP_InspectionPause'
CS_JBT_MODE_RINSE_RUN = 'RinseModeRunning'          #GCO
CS_JBT_MODE_CIP_RUN = 'CIPModeRunning'              #GCO
CS_JBT_MODE_SOAK_RUN = 'SoakModeRunning'            #GCO
CS_JBT_MODE_COOLDOWN_RUN = 'CooldownModeRunning'    #GCO
CS_JBT_RINSE_RUN= 'JBT_MODE_RINSE_RUN'              #TDO
CS_JBT_CIP_RUN= 'JBT_MODE_CIP_RUN'                  #TDO
CS_JBT_SOAK_RUN= 'JBT_MODE_SOAK_RUN'                #TDO
CS_JBT_COOLDOWN_RUN= 'JBT_MODE_COOLDOWN_RUN'        #TDO


cleaning_state_tags = [
    CS_CLEAN_MODE_RUNNING,
    CS_CLEAN_MODE_SELECTED,
    CS_SYSTEM_MASTER_STOP,
    CS_SYSTEM_MASTER_STOP_PB,
    CS_SYSTEM_MASTER_STOP_SW,
    CS_CIP_INSPECTION_PAUSE,
    CS_JBT_MODE_RINSE_RUN,
    CS_JBT_MODE_CIP_RUN,
    CS_JBT_MODE_SOAK_RUN,
    CS_JBT_MODE_COOLDOWN_RUN,
    CS_JBT_RINSE_RUN,
    CS_JBT_CIP_RUN,
    CS_JBT_SOAK_RUN,
    CS_JBT_COOLDOWN_RUN,
]
